### ISSUE TITLE
Setting CRON_TIME raises TypeError

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-api#105]
Setting the CRON_TIME variable raises a TypeError. This happens on Heroku and locally when I set the `CRON_TIME`. 

@tombh do you know if this fixed on the `oauth-login` branch? This hasn't been an issue because of the default setting is 5 mins anyway. cc @kamicut 

```
Running node worker.js on ⬢ oam-catalog... up, run.4530 (Standard-1X)
`openSet()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
/app/node_modules/node-cron/src/convert-expression/month-names-conversion.js:10
      expression = expression.replace(new RegExp(items[i], 'gi'), parseInt(i, 10) + 1);
                             ^

TypeError: Cannot read property 'replace' of undefined
    at convertMonthName (/app/node_modules/node-cron/src/convert-expression/month-names-conversion.js:10:30)
    at interprete (/app/node_modules/node-cron/src/convert-expression/month-names-conversion.js:16:23)
    at interprete (/app/node_modules/node-cron/src/convert-expression/index.js:38:22)
    at validate (/app/node_modules/node-cron/src/pattern-validation.js:49:29)
    at new Task (/app/node_modules/node-cron/src/task.js:38:5)
    at Object.createTask [as schedule] (/app/node_modules/node-cron/src/node-cron.js:19:16)
    at Object.<anonymous> (/app/worker.js:170:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by tombh** [comment]
Yes this is fixed in the `oauth-login` branch - I use it both for the staging server and the testing environment on Travis.

**Comment by smit1678** [comment]
👍  ok great, thanks
